### PR TITLE
Add PyCharm link to install

### PR DESCRIPTION
**Pull request by cheriesyb**

### CODE REVIEW

**Comment by joeratt** [comment]
Hi @cheriesyb  - thanks for the contribution!

I'm was hoping to make this an easy-to-use, automatic install for folks setting up their MacOS. Would you be interested in adding an automated install for pycharm as well? Maybe using a [Homebrew](https://brew.sh) cask?

https://formulae.brew.sh/cask/pycharm

**Comment by cheriesyb** [comment]
Hey @joeratt,
I've never created an automatic install but I could give it a go. It may take me some time given that I am busy at the moment. You're in no rush to have this completed right away?

**Comment by joeratt** [comment]
@cheriesyb  - no problem. The main script in this repo has examples of how that might work

https://github.com/joeratt/osx-init/blob/master/osx_init.sh

**Comment by cheriesyb** [comment]
@joeratt apologies for the delay, upon looking at the provided resource; homebrew, homebrew formula and the example main script. I am still unsure how to create the automatic install. Is it supposed to be a separate file or must incorporate content into a particular file?

**Comment by joeratt** [comment]
Whoops - sorry for the delay, @cheriesyb .

Most of the script is utilizing [homebrew Formula](https://brew.sh/) to do the installation. Most follow the following patterns:

```shell
brew install <application>

brew cask install <application>
```

the difference depends on how Homebrew supports a given application. I'd recommend taking a look at how it works :smile:

**Comment by joeratt** [comment]
I'm closing this PR, since we're a year later. Please feel free to reopen!

**Pull request closed without merging**
